### PR TITLE
Some very small improvement on frustum culling for mapblocks

### PR DESCRIPTION
**Pull request by Desour**
Moves code to do frustum culling with any camera scene node.
Disables frustum culling in drawlist update for now.

To really do the culling and everything correctly, there's much refactoring needed, too much for me for now.

Btw. camera offsets need to be updated.

### CODE REVIEW

**Comment by kilbith** [comment]
Thank you very much! Your patch makes it look better already.
@x2048 PTAL.

> Btw. camera offsets need to be updated.

They are already accounted in the camera internals. But I guess you mean in the frustrum culling code?

**Comment by Desour** [comment]
> > Btw. camera offsets need to be updated.
> 
> They are already accounted in the camera internals. But I guess you mean in the frustrum culling code?

Try using `/set_camera watch` and fly far away. At some point it looks like the camera was teleported, and moving back doesn't make it better.

AFAIK, camera scene node positions are relative to camera offset, so the universal-camera things need to be updated.
Or better, use the current camera's offset for the model matrix:
https://github.com/minetest/minetest/blob/b5c8850811fa3412b2d471073ec7a024ff6ce597/src/client/clientmap.cpp#L444

**Comment by kilbith** [comment]
Camera offset is set in the main camera code : https://github.com/minetest/minetest/blob/master/src/client/camera.cpp#L43

It is updated every `CAMERA_OFFSET_STEP` nodes. Camera offset is reachable from the client environment.

And believe me, I've spent **a lot** of time working with it and testing it.
https://github.com/kilbith/minetest/blob/camera-api/src/client/universalcamera.cpp#L419

> Try using /set_camera watch and fly far away. At some point it looks like the camera was teleported, and moving back doesn't make it better.

It's not teleported but the blocks are suddenly not visible anymore.
It's again an occlusion culling issue, not a positioning issue.

**Comment by Desour** [comment]
> And believe me, I've spent **a lot** of time working with it and testing it. https://github.com/kilbith/minetest/blob/camera-api/src/client/universalcamera.cpp#L419

Ah, I haven't seen that code.
But shouldn't `setCameraOffset` only subtract the difference of old and new offset?
https://github.com/kilbith/minetest/blob/b5c8850811fa3412b2d471073ec7a024ff6ce597/src/client/universalcamera.h#L125
(Maybe you tested with old offset (0,0,0).)

**Comment by kilbith** [comment]
No, the camera position is correct. What is happening with `/set_camera watch` is that ClientMap (or something else, idk) unloads the blocks from the initial position* which are far from the player, and don't reload them back when the player returns to the initial position*.

_* position where you executed the command._

**Pull request merged**
